import pyautogui
import time

#abrir o arquivos
pyautogui.alert('Não mexa em nada')
pyautogui.PAUSE = 0.9
pyautogui.press('win')
pyautogui.write('Explorador de Arquivos')
pyautogui.press('Enter')
time.sleep(1)
pyautogui.moveTo(676,133)
pyautogui.click()


#Area de Trabalho Win+d
pyautogui.hotkey('ctrl', 'v')
pyautogui.press('Enter')
pyautogui.moveTo(385,284)
#pyautogui.mouseInfo()
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste01')
pyautogui.press('Enter')

pyautogui.moveTo(400,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste02')
pyautogui.press('Enter')

pyautogui.moveTo(500,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste03')
pyautogui.press('Enter')

pyautogui.moveTo(600,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste04')
pyautogui.press('Enter')

pyautogui.moveTo(700,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste05')
pyautogui.press('Enter')

pyautogui.moveTo(800,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste06')
pyautogui.press('Enter')

pyautogui.moveTo(900,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste07')
pyautogui.press('Enter')

pyautogui.moveTo(1000,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste08')
pyautogui.press('Enter')

pyautogui.moveTo(1100,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste09')
pyautogui.press('Enter')

pyautogui.moveTo(1200,284)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste10')
pyautogui.press('Enter')

pyautogui.moveTo(385,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste11')
pyautogui.press('Enter')

pyautogui.moveTo(400,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste12')
pyautogui.press('Enter')

pyautogui.moveTo(500,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste13')
pyautogui.press('Enter')

pyautogui.moveTo(600,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste14')
pyautogui.press('Enter')

pyautogui.moveTo(700,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste15')
pyautogui.press('Enter')

pyautogui.moveTo(800,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste16')
pyautogui.press('Enter')

pyautogui.moveTo(900,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste17')
pyautogui.press('Enter')

pyautogui.moveTo(1000,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste18')
pyautogui.press('Enter')

pyautogui.moveTo(1100,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste19')
pyautogui.press('Enter')

pyautogui.moveTo(1200,380)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste20')
pyautogui.press('Enter')

pyautogui.moveTo(385,480)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste21')
pyautogui.press('Enter')

pyautogui.moveTo(400,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste22')
pyautogui.press('Enter')

pyautogui.moveTo(500,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste23')
pyautogui.press('Enter')

pyautogui.moveTo(600,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste24')
pyautogui.press('Enter')

pyautogui.moveTo(700,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste25')
pyautogui.press('Enter')

pyautogui.moveTo(800,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste26')
pyautogui.press('Enter')

pyautogui.moveTo(900,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste27')
pyautogui.press('Enter')

pyautogui.moveTo(1000,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste28')
pyautogui.press('Enter')

pyautogui.moveTo(1100,484)
pyautogui.click()
pyautogui.press('f2')
pyautogui.write('Teste29')
pyautogui.press('Enter')

pyautogui.alert('Terminado')
#pyautogui.moveTo(385,284)
#pyautogui.doubleClick()
